### ISSUE TITLE
No function matches version_compare2

### ISSUE THREAD

**Issue by jedahan** [repology/repology-updater#1037]
I installed libversion 3.0.1 and pip3 install libversion but still get the following when running `./repology-update.py --fetch --parse --database --postupdate --enabled-repositories kiss`

```
 ▲ ~/src/repology-updater ./repology-update.py --fetch --parse --database --postupdate --enabled-repositories kiss
May 04 19:04:01 loading rules
/home/micro/.local/lib/python3.8/site-packages/rpm.py:15: UserWarning: The RPM Python bindings are not currently available via PyPI.

Please install them with your distro package manager (typically called
'python2-rpm' or 'python3-rpm'), and ensure that any virtual environments
needing the API are configured to be able to see the system site packages
directory.

  warnings.warn(warning_msg)
May 04 19:04:02 updating repositories metadata
May 04 19:04:02   committing changes
May 04 19:04:02 fetching kiss_community
May 04 19:04:02   done (no changes)
May 04 19:04:06 parsing kiss_community
May 04 19:04:09   done
May 04 19:04:09 fetching kiss_main
May 04 19:04:10   done (no changes)
May 04 19:04:10 parsing kiss_main
May 04 19:04:12   done
May 04 19:04:12 starting the update
May 04 19:04:12 updating projects
May 04 19:04:12   at "2bwm": added 1, removed 0, changed 0, unchanged 0, total change 100.00%
May 04 19:04:12   done: added 443, removed 0, changed 0, unchanged 0, total change 100.00%
May 04 19:04:12 updating field statistics
May 04 19:04:12 update mode is full,explicit analyze is enabled
May 04 19:04:12 preparing updated packages
May 04 19:04:12 updating projects
May 04 19:04:12 updating maintainers (precreate)
May 04 19:04:12 updating maintainers
May 04 19:04:12 updating repositories
May 04 19:04:12 updating tracks
May 04 19:04:12 updating track versions
May 04 19:04:12 updating project releases
May 04 19:04:12 updating project events
Traceback (most recent call last):
  File "./repology-update.py", line 373, in <module>
    sys.exit(main())
  File "./repology-update.py", line 356, in main
    database_update(env)
  File "./repology-update.py", line 257, in database_update
    update.push_packages(env.get_repo_processor().iter_parsed(reponames=env.get_enabled_repo_names(), logger=logger))
  File "/home/micro/src/repology-updater/repology/update/__init__.py", line 234, in __exit__
    self._finish_update()
  File "/home/micro/src/repology-updater/repology/update/__init__.py", line 144, in _finish_update
    self._database.update_project_events(self._history_cutoff_timestamp)
  File "/home/micro/src/repology-updater/repology/querymgr.py", line 277, in do_query
    cursor.execute(render, arguments)
psycopg2.errors.UndefinedFunction: function version_compare2(text, text) does not exist
LINE 4:    version_compare2(old[1], new[1]) != 0
           ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT (
			old IS NOT NULL AND
			new IS NOT NULL AND
			version_compare2(old[1], new[1]) != 0
		) OR (old IS NULL) != (new IS NULL)
CONTEXT:  PL/pgSQL function version_set_changed(text[],text[]) line 3 at RETURN
```

**Comment by AMDmi3** [comment]
Have you installed https://github.com/repology/postgresql-libversion?

**Comment by jedahan** [comment]
just installed it, and did create_extension, and it worked, thanks!
