### ISSUE TITLE
syntax error at or near "MATERIALIZED"

### ISSUE THREAD

**Issue by raz3k** [repology/repology-updater#1420]
Hello all,

First of all thank you for repology. 

I am having issues with the latest code from the main branch.

I have ran `./repology-update.py --fetch --parse --database --postupdate`

And after it does all what it needs I get this:

```Aug 09 16:04:21 updating url relations (all)
Aug 09 16:05:45 updating url relations (filtered)
Aug 09 16:05:49 updating projects has_related flag
Aug 09 16:05:52 updating problems
Aug 09 16:09:34 updating repository problem counts
Aug 09 16:09:39 updating repository maintainers
Aug 09 16:11:11 updating repository maintainer counts
Traceback (most recent call last):
  File "/home/cloud-user/repology-updater/./repology-update.py", line 410, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cloud-user/repology-updater/./repology-update.py", line 390, in main
    database_update(env)
  File "/home/cloud-user/repology-updater/./repology-update.py", line 288, in database_update
    with UpdateProcess(database, logger) as update:
  File "/home/cloud-user/repology-updater/repology/update/__init__.py", line 265, in __exit__
    self._finish_update()
  File "/home/cloud-user/repology-updater/repology/update/__init__.py", line 235, in _finish_update
    self._database.update_repositories_maintainer_counts()
  File "/home/cloud-user/repology-updater/repology/querymgr.py", line 277, in do_query
    cursor.execute(render, arguments)
psycopg2.errors.SyntaxError: syntax error at or near "MATERIALIZED"
LINE 19: WITH repository_maintainer_counts AS MATERIALIZED (`
```

I also tried importing the dump using this: `curl -s https://dumps.repology.org/repology-database-dump-latest.sql.zst | unzstd | psql -U repology` but after it finishes I get no results in the database.

How can I proceed further?

Thanks!

**Comment by AMDmi3** [comment]
Which postgresql version do you use?

**Comment by raz3k** [comment]
yeah, that's the issue, thanks, I was using PostgreSQL 10.
